# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('icon', models.ImageField(upload_to=b'')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', '\u7537\u6027'), ('F', '\u5973\u6027'), ('U', '\u4fdd\u5bc6')], max_length=8)),
            ],
        ),
    ]
